#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
#sudo service nginx start
sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bkcp

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '24i\	 rewrite ^/redirect_me http://www.youtube.com/watch?v=QH2-TGUwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart

echo -e "\nCompleted.\n"
