#!/usr/bin/env bash

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf

sudo service nginx restart
